name: Auto Merge main into main-plugin
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main-test
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Create and push sync branch
        run: |
          git checkout -b sync-main-to-main-plugin
          git push origin sync-main-to-main-plugin

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main-plugin
          title: "Automated PR: Merge main into main-plugin"
          body: "This pull request was automatically created to merge changes from main into main-plugin."
          branch: sync-main-to-main-plugin
          delete-branch: true
