name: Auto Merge main into main-plugin
on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Git
        # Set up bot account to commit automated changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Checkout main-plugin branch
        run: git checkout main-plugin

      - name: Merge main into main-plugin
        # --no-ff: Always create a merge commit to maintain a clear history of merges.
        # --no-edit: Don't prompt but use the default merge message.
        run: git merge main --no-ff --no-edit

      - name: Push changes
        run: git push origin main-plugin
        env:
          # `GITHUB_TOKEN` is automatically available on Github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
